services:
  db:
    image: mcr.microsoft.com/mssql/server:2022-preview-ubuntu-22.04
    container_name: manejo-presupuesto
    environment:
        ACCEPT_EULA: Y
        MSSQL_SA_PASSWORD: Dramatic2091
    ports:
        - 1433:1433
    volumes:
        - manejopresupuesto:/var/opt/mssql

volumes:
  manejopresupuesto:
    external: true